<a href="https://colab.research.google.com/github/nicolasdemo22332445/RNN/blob/main/Ecuaciones_no_Lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejemplo 1: Eliminacion de Gauss

In [6]:
import numpy as np

# Matriz de coeficientes
A = np.array([[2,3,1],
             [4,1,2],
             [3,4,2]], dtype=float)

#Vector de terminos independienmtes
b = np.array([1,2,3], dtype=float)

#Resolvemos el sistema de ecuaciones usando eliminacion de Gauss
sol = np.linalg.solve(A, b)

#Mostrar la solucion
print("Solucion del sistema:")
print(f"x = {sol[0]:.4f}, y = {sol[1]:.4f}, z = {sol[2]:.4f}")


Solucion del sistema:
x = -1.0000, y = -0.0000, z = 3.0000


Ejemplo 2: Matriz Inversa para calcular los pesos ajustados

In [7]:
#Matriz de coeficientes
A = np.array([[1,2,3],
              [2,1,4],
              [3,4,1]], dtype=float)

#Vcetor de salida deseada
b = np.array([4,6,7], dtype=float)

#Calcular la matriz inversa
A_inv = np.linalg.inv(A)

#Multiplicar A inv por el vector b
sol = np.dot(A_inv, b)

#Mostrar la solucion
print("Pesos ajustados: ")
print(f"w1 = {sol[0]:.4f}, w2 = {sol[1]:.4f}, w3 = {sol[2]:.4f}")

Pesos ajustados: 
w1 = 1.7500, w2 = 0.3000, w3 = 0.5500


Ejercicio 3: Metodo de Jacobi

In [11]:
def jacobi(A, B, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if i != j)
            x_new[i] = (b[i] - s) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new
        x = x_new
    return x

#Matriz de coeficientes
A = np.array([[10,-1,2],
              [-1,11,-1],
              [2,-1,10]], dtype=float)

#Vector de errores
b = np.array([0.6, 1.5, 2.1], dtype=float)

#Aproximacion inicial
x0 = np.zeros_like(b)

#Aplicar el metodo de jacobi
sol = jacobi(A,b, x0)

print("Pesos ajustados usando Jacobi")
print(sol)

Pesos ajustados usando Jacobi
[0.03201923 0.15923077 0.21951923]


Ejemplo 4: Metodo Iterativo de Gauss-Seidel

In [13]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-10, max_iter=1000):
  n = len(b)
  x = x0
  for k in range(max_iter):
      x_new = np.copy(x)
      for i in range(n):
          s1 = sum(A[i][j] * x_new[j] for j in range(i))
          s2 = sum(A[i][j] * x[j] for j in range(i+1, n))
      if np.linalg.norm(x_new - x, ord=np.inf) < tol:
          return x_new, k
      x = x_new
  return x, max_iter

#Matriz de coeficinetes
A = np.array([[10,-1,2,0],
              [-1,11,-1,3],
              [2,-1,10,-1],
              [0,3,-1,8]], dtype=float)

#Vector de terminos independientes
b = np.array([6, 25, -11, 15], dtype=float)

#Valor inicial de las incognitas
x0 = np.zeros_like(b)

#Resolver el sistema usando el metodo de Gauss-Seidel
sol, iteraciones = gauss_seidel(A , b, x0)

#Mostrar la solucion y el numero de iteraciones
print("Solucion del sistema: ")
print(sol)
print(f"Numero de iteraciones: {iteraciones}")

Solucion del sistema: 
[0. 0. 0. 0.]
Numero de iteraciones: 0


Ejemplo 5: Descomposicion de Cholesky aplicada a una red neuronal

In [17]:
from scipy.linalg import cholesky

#Matriz y vector
A = np.array([[6,15,55],
              [15,55,255],
              [55,225,979]], dtype=float)

b = np.array([76, 295, 1295], dtype=float)

#Descomposicion de cholesky
L = cholesky(A, lower=True)

#Resolver Ly = b
y = np.linalg.solve(L, b)

#Resolver L^T x = y
x = np.linalg.solve(L.T, y)

print("Pesos ajustados usando Cholesky: ")
print(x)

Pesos ajustados usando Cholesky: 
[ 4.21428571 -3.82142857  1.96428571]
